Residential[] = {
	{Loot_WEAPON,		6,		MeleeBaseBallBat},
	{Loot_WEAPON,		6,		ItemFishingPole},
	{Loot_VEHICLE,		8,		WeaponHolder_MeleeMachete},		
	{Loot_WEAPON,		6,		ItemFlashlight},
	{Loot_WEAPON,		6,		Binocular},
	{Loot_GROUP,		4,		backpacksCivil},
	{Loot_PILE,			6,		AmmoCivilian, 1, 2},
	{Loot_PILE,			9,		Trash, 1, 3},
	//{Loot_MAGAZINE,		4,		ItemTrashPaper},
	//{Loot_MAGAZINE,		4,		ItemTrashPaperMusic},	
	{Loot_PILE,			9,		Consumable, 1, 2},
	{Loot_GROUP,		5,		clothes},
	{Loot_GROUP,		3,		WeaponsCivilian},
	{Loot_GROUP,		3,		tents},
	{Loot_GROUP,		3,		toolsMatchbox},
	{Loot_MAGAZINE,		5,		ItemNewspaper},		
	{Loot_MAGAZINE,		4,		ItemBriefcaseEmpty},		
	{Loot_GROUP,		1,		briefcaseGold},	
	{Loot_GROUP,		7,		Generic}
};

ResidentialSmall[] = {
	{Loot_WEAPON,		3,		ItemMap},
	{Loot_WEAPON,		3,		ItemWatch},
	{Loot_WEAPON,		3,		ItemCompass},
	{Loot_GROUP,		3,		toolsKnife},
	{Loot_MAGAZINE,		0.1,	ItemHotwireKit},	
	//{Loot_MAGAZINE,		4,		equip_aa_battery},
	//{Loot_MAGAZINE,		4,		equip_d_battery},
	{Loot_MAGAZINE,		5,		ItemKosmosSmokesOpen},
	{Loot_MAGAZINE,		5,		ItemKosmosSmokes},	
	{Loot_MAGAZINE,		5,		ItemBook1},	
	{Loot_MAGAZINE,		5,		ItemBook2},	
	{Loot_MAGAZINE,		5,		ItemBook3},	
	{Loot_MAGAZINE,		5,		ItemBook4},	
	{Loot_MAGAZINE,		5,		ItemLetter},
	//{Loot_MAGAZINE,		4,		ItemTrashPaper},
	//{Loot_MAGAZINE,		4,		ItemTrashPaperMusic},		
	{Loot_MAGAZINE,		2,		ItemMorphine},
	{Loot_MAGAZINE,		3,		ItemHeatPack},
	{Loot_MAGAZINE,		3,		ItemBandage},	
	{Loot_MAGAZINE,		2,		ItemPainkiller},		
	{Loot_MAGAZINE,		5,		ItemBookBible},		
	{Loot_GROUP,		2,		AmmoCivilian},
	{Loot_GROUP,		6,		Trash},
	{Loot_GROUP,		6,		Consumable},
	{Loot_GROUP,		3,		AttachmentsGeneric},
	{Loot_GROUP,		1,		Antibiotics},	
	{Loot_GROUP,		3,		toolsMatchbox},
	{Loot_GROUP,		6,		GenericSmall}
};
